baseURL = "https://example.com"
defaultContentLanguage = "en"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT", "404"]
theme = "hugo-product-launch"
title = "Quack The Code"
[markup.goldmark.renderer]
hardWraps = true
[params]
copyright = "© Quack The Code"
description = "Rubber ducks that hear your bugs."
favicon = "/favicon-32x32.png"
hidedesignbyline = false
images = ["images/share-image.png"]
title = "Quack The Code"
[params.meta]
keywords = "Rubber Duck, Debugging, Quack the code, Rubber duck debugging, duck debugging, software development, software debugging, software bugs"
